spring.datasource.url=jdbc:postgresql://localhost:5432/ledger_db
spring.datasource.username=postgres
spring.datasource.password=ketchap
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=never
server.port=8081